### PR TITLE
Add some resources link 

### PR DESCRIPTION
**Pull request by JBonifay**
Hi Valentina !

I'm adding some book reference link as they are I think really good!

### CODE REVIEW

**Comment by JBonifay** [comment]
I'm wondering if Uncle bob link should go to courses instead

**Comment by valentinajemuovic** [comment]
Thanks @JBonifay! Yes, it could go under courses perhaps.

Also, I've added one more step for contributing, you can add your name to the contributors list, see instructions here.

After that, I can merge the PR.

**Comment by JBonifay** [comment]
Done ! thanks :)

**Comment by valentinajemuovic** [comment]
Great, thanks!

**Pull request merged**
